const starsData = [
  {
    name: "Sirius",
    description: "The brightest star in the night sky, also known as the Dog Star.",
    lifespan: "100 million years",
    distanceFromEarth: "8.6 light-years",
    diameter: "1.711 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During winter nights",
    directionOrConstellation: "Canis Major",
  },
  {
    name: "Betelgeuse",
    description: "A red supergiant star in the Orion constellation.",
    lifespan: "8-10 million years",
    distanceFromEarth: "640 light-years",
    diameter: "1.5 billion km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During winter months",
    directionOrConstellation: "Orion",
  },
  {
    name: "Vega",
    description: "A bright star in the Lyra constellation.",
    lifespan: "1 billion years",
    distanceFromEarth: "25 light-years",
    diameter: "2.362 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During summer nights",
    directionOrConstellation: "Lyra",
  },
  {
    name: "Alpha Centauri",
    description: "The closest star system to the Solar System.",
    lifespan: "1 trillion years",
    distanceFromEarth: "4.37 light-years",
    diameter: "1.6 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During summer nights",
    directionOrConstellation: "Centaurus",
  },
  {
    name: "Arcturus",
    description: "A red giant star in the Bootes constellation.",
    lifespan: "10-12 billion years",
    distanceFromEarth: "37 light-years",
    diameter: "27.1 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During summer nights",
    directionOrConstellation: "Bootes",
  },
  {
    name: "Rigel",
    description: "The brightest star in the Orion constellation.",
    lifespan: "10 million years",
    distanceFromEarth: "860 light-years",
    diameter: "116 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During winter months",
    directionOrConstellation: "Orion",
  },
  {
    name: "Antares",
    description: "A red supergiant star in the Scorpius constellation.",
    lifespan: "10-20 million years",
    distanceFromEarth: "550 light-years",
    diameter: "883 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During summer nights",
    directionOrConstellation: "Scorpius",
  },
  {
    name: "Pollux",
    description: "A giant star in the Gemini constellation.",
    lifespan: "1.5 billion years",
    distanceFromEarth: "34 light-years",
    diameter: "10.3 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During winter nights",
    directionOrConstellation: "Gemini",
  },
  {
    name: "Altair",
    description: "A bright star in the Aquila constellation.",
    lifespan: "1 billion years",
    distanceFromEarth: "16.7 light-years",
    diameter: "2.6 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During summer nights",
    directionOrConstellation: "Aquila",
  },
  {
    name: "Fomalhaut",
    description: "A young star in the Piscis Austrinus constellation.",
    lifespan: "1-2 billion years",
    distanceFromEarth: "25 light-years",
    diameter: "1.9 million km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "During autumn nights",
    directionOrConstellation: "Piscis Austrinus",
  },
];

module.exports = starsData;
