const planetsData = [
  {
    name: "Mercury",
    description: "The smallest and closest planet to the Sun.",
    lifespan: "4.5 billion years",
    distanceFromSun: "57.9 million km",
    diameter: "4,880 km",
    yearOfDiscovery: "Known to ancient civilizations",
    bestViewingTimeFromIndia: "During the evening, close to the horizon",
    directionOrConstellation: "Western horizon",
  },
  {
    name: "Venus",
    description: "Known as Earth's sister planet, it is the hottest planet in our solar system.",
    lifespan: "4.6 billion years",
    distanceFromSun: "108.2 million km",
    diameter: "12,104 km",
    yearOfDiscovery: "Known to ancient civilizations",
    bestViewingTimeFromIndia: "Early morning or late evening",
    directionOrConstellation: "Eastern horizon",
  },
  {
    name: "Earth",
    description: "Our home planet, the only known planet with life.",
    lifespan: "About 4.54 billion years",
    distanceFromSun: "149.6 million km",
    diameter: "12,742 km",
    yearOfDiscovery: "Known since ancient times",
    bestViewingTimeFromIndia: "N/A (always visible)",
    directionOrConstellation: "N/A (always visible)",
  },
  {
    name: "Mars",
    description: "Often referred to as the 'Red Planet,' it is a potential candidate for human colonization.",
    lifespan: "About 4.6 billion years",
    distanceFromSun: "227.9 million km",
    diameter: "6,779 km",
    yearOfDiscovery: "Known to ancient civilizations",
    bestViewingTimeFromIndia: "During its opposition",
    directionOrConstellation: "Eastern horizon",
  },
  {
    name: "Jupiter",
    description: "The largest planet in our solar system, known for its massive storm called the Great Red Spot.",
    lifespan: "About 4.5 billion years",
    distanceFromSun: "778.5 million km",
    diameter: "139,822 km",
    yearOfDiscovery: "Known to ancient civilizations",
    bestViewingTimeFromIndia: "During its opposition",
    directionOrConstellation: "Eastern horizon",
  },
  {
    name: "Saturn",
    description: "Famous for its spectacular ring system, it is the second-largest planet in our solar system.",
    lifespan: "About 4.6 billion years",
    distanceFromSun: "1.4 billion km",
    diameter: "116,464 km",
    yearOfDiscovery: "Known to ancient civilizations",
    bestViewingTimeFromIndia: "During its opposition",
    directionOrConstellation: "Eastern horizon",
  },
  {
    name: "Uranus",
    description: "The seventh planet from the Sun, it rotates on its side and is often referred to as the 'ice giant.'",
    lifespan: "About 4.5 billion years",
    distanceFromSun: "2.9 billion km",
    diameter: "50,724 km",
    yearOfDiscovery: "Discovered in 1781",
    bestViewingTimeFromIndia: "Requires a telescope",
    directionOrConstellation: "Aries",
  },
  {
    name: "Neptune",
    description: "The eighth and farthest planet from the Sun.",
    lifespan: "About 4.5 billion years",
    distanceFromSun: "4.5 billion km",
    diameter: "49,244 km",
    yearOfDiscovery: "Discovered in 1846",
    bestViewingTimeFromIndia: "Requires a telescope",
    directionOrConstellation: "Aquarius",
  },
];


module.exports = planetsData;
