const galaxiesData = [
  {
    name: "Milky Way",
    description: "The galaxy that contains our Solar System.",
    type: "Barred spiral galaxy",
    age: "13.6 billion years",
    diameter: "100,000 light-years",
    discoveryYear: "Known since ancient times",
    bestViewingTimeFromIndia: "Throughout the year",
    direction: "Visible as a band across the sky",
  },
  {
    name: "Andromeda Galaxy",
    description: "The nearest spiral galaxy to the Milky Way.",
    type: "Spiral galaxy",
    age: "7.1 billion years",
    diameter: "220,000 light-years",
    discoveryYear: "964 CE (by Al-Sufi)",
    bestViewingTimeFromIndia: "During autumn nights",
    direction: "Andromeda constellation",
  },
  {
    name: "Triangulum Galaxy",
    description: "A spiral galaxy in the Local Group.",
    type: "Spiral galaxy",
    age: "4.6 billion years",
    diameter: "60,000 light-years",
    discoveryYear: "1784 (by Charles Messier)",
    bestViewingTimeFromIndia: "During autumn nights",
    direction: "Triangulum constellation",
  },
  {
    name: "Sombrero Galaxy",
    description: "A galaxy with a bright nucleus and a dark dust lane.",
    type: "Spiral galaxy",
    age: "8-10 billion years",
    diameter: "50,000 light-years",
    discoveryYear: "1781 (by Pierre Méchain)",
    bestViewingTimeFromIndia: "During spring nights",
    direction: "Virgo constellation",
  },
  {
    name: "Whirlpool Galaxy",
    description: "A pair of interacting galaxies.",
    type: "Spiral galaxy",
    age: "Unknown",
    diameter: "60,000 light-years",
    discoveryYear: "1773 (by Charles Messier)",
    bestViewingTimeFromIndia: "During spring nights",
    direction: "Canes Venatici constellation",
  },
  {
    name: "Bode's Galaxy (M81)",
    description: "A grand design spiral galaxy.",
    type: "Spiral galaxy",
    age: "Unknown",
    diameter: "90,000 light-years",
    discoveryYear: "1774 (by Johann Elert Bode)",
    bestViewingTimeFromIndia: "During spring nights",
    direction: "Ursa Major constellation",
  },
  {
    name: "Cigar Galaxy (M82)",
    description: "A starburst galaxy undergoing intense star formation.",
    type: "Starburst galaxy",
    age: "Unknown",
    diameter: "37,000 light-years",
    discoveryYear: "1774 (by Johann Elert Bode)",
    bestViewingTimeFromIndia: "During spring nights",
    direction: "Ursa Major constellation",
  },
  {
    name: "Large Magellanic Cloud",
    description: "A satellite galaxy of the Milky Way.",
    type: "Irregular galaxy",
    age: "Unknown",
    diameter: "14,000 light-years",
    discoveryYear: "1503 (by Amerigo Vespucci)",
    bestViewingTimeFromIndia: "During autumn and winter nights",
    direction: "Dorado constellation",
  },
  {
    name: "Small Magellanic Cloud",
    description: "A dwarf galaxy near the Large Magellanic Cloud.",
    type: "Irregular galaxy",
    age: "Unknown",
    diameter: "7,000 light-years",
    discoveryYear: "Unknown",
    bestViewingTimeFromIndia: "During autumn and winter nights",
    direction: "Tucana constellation",
  },
  {
    name: "Sculptor Galaxy",
    description: "A dwarf galaxy in the Sculptor Group.",
    type: "Dwarf galaxy",
    age: "Unknown",
    diameter: "5,000 light-years",
    discoveryYear: "1937 (by Harlow Shapley)",
    bestViewingTimeFromIndia: "During autumn nights",
    direction: "Sculptor constellation",
  },
];

module.exports = galaxiesData;
